preset: recommended

risky: true

enabled:
  - concat_with_spaces
  - const_separation
  - const_visibility_required
  - fully_qualified_strict_types
  - linebreak_after_opening_tag
  - logical_operators
  - modernize_types_casting
  - multiline_comment_opening_closing
  - no_blank_lines_after_return
  - no_extra_block_blank_lines
  - no_useless_else
  - non_printable_character
  - nullable_type_declarations
  - phpdoc_add_missing_param_annotation
  - phpdoc_link_to_see
  - phpdoc_types_null_last
  - short_list_syntax
  - simple_to_complex_string_variable
  - strict_comparison

disabled:
  - align_double_arrow
  - concat_without_spaces
  - no_unneeded_control_parentheses
  # PHP documentation should not be that strict
  - phpdoc_align
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_order
  - phpdoc_separation
