name: "Run Tests"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, 8.0, 8.1, 8.2]
        laravel: [6, 7, 8, 9, 10]
        exclude:
          - php: 7.3
            laravel: 9
          - php: 7.3
            laravel: 10
          - php: 7.4
            laravel: 9
          - php: 7.4
            laravel: 10
          - php: 8.0
            laravel: 10
          - php: 8.1
            laravel: 6
          - php: 8.1
            laravel: 7
          - php: 8.2
            laravel: 6
          - php: 8.2
            laravel: 7
          - php: 8.2
            laravel: 8

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, redis, zip
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Run PHPCS tests
        run: vendor/bin/phpcs src tests/Unit --standard=PSR12

      - name: Run test suite
        run: vendor/bin/phpunit
